[build-system]
requires = ["flit_core >=3.8,<5"]
build-backend = "flit_core.buildapi"

[tool.libdoc2testbench]
# output_path = "dump1.zip"
attachment = false
# created_datatypes = "ALL"
# documentation_format = "HTML"
# library_name_extension = "[Robot-Library]"
library_root = "Robot"
# repository_id ="itb-RF"
# resource_name_extension = "[Robot-Resource]"
resource_root = "Robot"
# specification_format = "RAW"
excluded_paths = [
  # "**/test_libraries",
  "**/libdoc2testbench"
]


[project]
name = "robotframework-libdoc2testbench"
authors = [{name = "imbus AG", email = "support@imbus.de"}]
description = "Robot Framework Libdoc Extension that generates imbus TestBench Library import formats."
requires-python = ">= 3.9"
readme = "README.md"
license = {text = "Apache 2.0 License"}
dynamic = ["version"]
classifiers = [
  "Environment :: Console",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Operating System :: OS Independent",
  "License :: OSI Approved :: Apache Software License",
  "Topic :: Software Development :: Testing",
  "Topic :: Software Development :: Testing :: Acceptance",
  "Framework :: Robot Framework"
]
dependencies = [
  "robotframework >= 5.0",
  "xsdata",
  "tomli; python_version < '3.11'",
]


[project.urls]
Homepage = "https://github.com/imbus/robotframework-libdoc2testbench"


[project.scripts]
libdoc2testbench = "libdoc2testbench.__main__:run"
Libdoc2TestBench = "libdoc2testbench.__main__:run"

[tool.flit.module]
name = "libdoc2testbench"


[tool.flit.sdist]
include = [
    "libdoc2testbench/**/*.json",
]


[project.optional-dependencies]
dev = [
  "build",
  "check-manifest",
  "xsdata[cli]",
  "flit",
  "invoke",
  "mypy",
  "pylint",
  "pytest",
  "pytest-cov",
  "pytest-spec",
  "ruff",
]

[tool.mypy]
python_version = "3.9"
ignore_missing_imports = true
no_implicit_optional = true
strict_optional = true
warn_return_any = true
warn_no_return = true
warn_unreachable = true
pretty = true
exclude = [
  "test_libraries/",
  "libdoc2testbench/project_dump_model/"
]


[tool.ruff]
line-length = 100
unfixable = [
    "UP007"
]
exclude = [
  "__pycache__",
  "config.py",
  "model.py",
  "tests",
  "itb_project_export.py"
]
ignore = [
  "T201",
  "N806",
  "B904",
  "B008", # Todo: fix later
  "PLR0913", # Todo: fix later
]
target-version = "py39"
select = [
  "E",
  "F",
  "W",
  "C90",
  "I",
  "N",
  "B",
  "PYI",
  "PL",
  "PTH",
  "UP",
  "A",
  "C4",
  "DTZ",
  "ISC",
  "ICN",
  "INP",
  "PIE",
  "T20",
  "PYI",
  "PT",
  "RSE",
  "RET",
  "SIM",
  "RUF"
]